2023-12-16 10:48:51,043 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Sat, 16 Dec 2023 10:48:50 +0000. Up 5.96 seconds.
2023-12-16 10:48:51,043 - main.py[DEBUG]: No kernel command line url found.
2023-12-16 10:48:51,043 - main.py[DEBUG]: Closing stdin.
2023-12-16 10:48:51,046 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2023-12-16 10:48:51,047 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-12-16 10:48:51,070 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2023-12-16 10:48:51,071 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-12-16 10:48:51,073 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2023-12-16 10:48:51,074 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-12-16 10:48:51,077 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2023-12-16 10:48:51,077 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-12-16 10:48:51,092 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2023-12-16 10:48:51,092 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2023-12-16 10:48:51,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2023-12-16 10:48:51,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-12-16 10:48:51,117 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2023-12-16 10:48:51,118 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-12-16 10:48:51,137 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2023-12-16 10:48:51,137 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-12-16 10:48:51,158 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2023-12-16 10:48:51,159 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2023-12-16 10:48:51,191 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2023-12-16 10:48:51,191 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2023-12-16 10:48:51,192 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2023-12-16 10:48:51,193 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2023-12-16 10:48:51,193 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2023-12-16 10:48:51,194 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2023-12-16 10:48:51,195 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2023-12-16 10:48:51,195 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2023-12-16 10:48:51,196 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2023-12-16 10:48:51,196 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2023-12-16 10:48:51,197 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2023-12-16 10:48:51,197 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:51,212 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:51,220 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2023-12-16 10:48:51,230 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2023-12-16 10:48:51,230 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-12-16 10:48:51,230 - stages.py[DEBUG]: no cache found
2023-12-16 10:48:51,230 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2023-12-16 10:48:51,231 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-12-16 10:48:51,261 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-12-16 10:48:51,261 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2023-12-16 10:48:51,269 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2023-12-16 10:48:51,269 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2023-12-16 10:48:51,269 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2023-12-16 10:48:51,269 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-12-16 10:48:51,269 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2023-12-16 10:48:51,270 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2023-12-16 10:48:51,270 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2023-12-16 10:48:51,270 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2023-12-16 10:48:51,270 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2023-12-16 10:48:51,270 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2023-12-16 10:48:51,270 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2023-12-16 10:48:51,270 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2023-12-16 10:48:51,270 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2023-12-16 10:48:51,270 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2023-12-16 10:48:51,270 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2023-12-16 10:48:51,271 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2023-12-16 10:48:51,296 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2023-12-16 10:48:51,296 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2023-12-16 10:48:51,296 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,305 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2023-12-16 10:48:51,305 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2023-12-16 10:48:51,306 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,310 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2476b) after 1 attempts
2023-12-16 10:48:51,311 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,314 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 318b) after 1 attempts
2023-12-16 10:48:51,314 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,322 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2023-12-16 10:48:51,322 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,335 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
2023-12-16 10:48:51,335 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,338 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2023-12-16 10:48:51,338 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,355 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2023-12-16 10:48:51,355 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,365 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2023-12-16 10:48:51,365 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,371 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2023-12-16 10:48:51,371 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,385 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2023-12-16 10:48:51,385 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,388 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2023-12-16 10:48:51,389 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,405 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 211b) after 1 attempts
2023-12-16 10:48:51,405 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,413 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2023-12-16 10:48:51,413 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,417 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2023-12-16 10:48:51,418 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,423 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2023-12-16 10:48:51,423 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,430 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2023-12-16 10:48:51,431 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,446 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2023-12-16 10:48:51,446 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,451 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2023-12-16 10:48:51,451 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,454 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2023-12-16 10:48:51,454 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,462 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2023-12-16 10:48:51,463 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,477 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ (200, 230b) after 1 attempts
2023-12-16 10:48:51,477 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,480 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/ (200, 12b) after 1 attempts
2023-12-16 10:48:51,481 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/3.79.104.105' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/3.79.104.105', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,495 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/ipv4-associations/3.79.104.105 (200, 13b) after 1 attempts
2023-12-16 10:48:51,495 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,500 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/device-number (200, 1b) after 1 attempts
2023-12-16 10:48:51,500 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,508 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/interface-id (200, 21b) after 1 attempts
2023-12-16 10:48:51,508 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,526 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-hostname (200, 46b) after 1 attempts
2023-12-16 10:48:51,526 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,535 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/local-ipv4s (200, 13b) after 1 attempts
2023-12-16 10:48:51,536 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,539 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/mac (200, 17b) after 1 attempts
2023-12-16 10:48:51,539 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,555 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/owner-id (200, 12b) after 1 attempts
2023-12-16 10:48:51,555 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,564 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-hostname (200, 51b) after 1 attempts
2023-12-16 10:48:51,564 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,566 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/public-ipv4s (200, 12b) after 1 attempts
2023-12-16 10:48:51,567 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,571 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-group-ids (200, 41b) after 1 attempts
2023-12-16 10:48:51,571 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,584 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/security-groups (200, 64b) after 1 attempts
2023-12-16 10:48:51,585 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,593 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-id (200, 24b) after 1 attempts
2023-12-16 10:48:51,593 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,596 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2023-12-16 10:48:51,596 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,605 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-id (200, 21b) after 1 attempts
2023-12-16 10:48:51,605 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,610 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2023-12-16 10:48:51,611 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,613 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:af:cb:a4:36:ed/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2023-12-16 10:48:51,613 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,623 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2023-12-16 10:48:51,623 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,639 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 13b) after 1 attempts
2023-12-16 10:48:51,640 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,651 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2023-12-16 10:48:51,651 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,654 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 12b) after 1 attempts
2023-12-16 10:48:51,654 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,661 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/ (200, 19b) after 1 attempts
2023-12-16 10:48:51,661 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,664 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key (200, 399b) after 1 attempts
2023-12-16 10:48:51,664 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,671 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2023-12-16 10:48:51,671 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,673 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2023-12-16 10:48:51,673 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,680 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2023-12-16 10:48:51,681 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2023-12-16 10:48:51,684 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,690 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2023-12-16 10:48:51,691 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,693 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2023-12-16 10:48:51,693 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,700 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 46b) after 1 attempts
2023-12-16 10:48:51,701 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,703 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2023-12-16 10:48:51,703 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,710 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2023-12-16 10:48:51,710 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,713 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2023-12-16 10:48:51,713 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,716 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2023-12-16 10:48:51,716 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,721 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 46b) after 1 attempts
2023-12-16 10:48:51,721 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,724 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2023-12-16 10:48:51,724 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,727 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2023-12-16 10:48:51,727 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,730 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2023-12-16 10:48:51,731 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,741 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 51b) after 1 attempts
2023-12-16 10:48:51,741 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,745 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 12b) after 1 attempts
2023-12-16 10:48:51,745 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,747 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2023-12-16 10:48:51,747 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,751 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 64b) after 1 attempts
2023-12-16 10:48:51,751 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,760 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 33b) after 1 attempts
2023-12-16 10:48:51,761 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,764 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2023-12-16 10:48:51,764 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,766 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1495b) after 1 attempts
2023-12-16 10:48:51,767 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,770 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1175b) after 1 attempts
2023-12-16 10:48:51,771 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2023-12-16 10:48:51,781 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 483b) after 1 attempts
2023-12-16 10:48:51,781 - util.py[DEBUG]: Crawl of metadata service took 0.511 seconds
2023-12-16 10:48:51,784 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2023-12-16 10:48:51,784 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2023-12-16 10:48:51,785 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2023-12-16 10:48:51,785 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2023-12-16 10:48:51,786 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpj5b6k0yk) - w: [600] 13054 bytes/chars
2023-12-16 10:48:51,787 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpc87romg4) - w: [644] 8912 bytes/chars
2023-12-16 10:48:51,787 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2023-12-16 10:48:51,787 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2023-12-16 10:48:51,787 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-12-16 10:48:51,787 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2023-12-16 10:48:51,787 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,806 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-12-16 10:48:51,806 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-12-16 10:48:51,806 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,807 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-12-16 10:48:51,807 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-12-16 10:48:51,807 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,808 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-12-16 10:48:51,809 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-12-16 10:48:51,809 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,822 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-12-16 10:48:51,822 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-12-16 10:48:51,822 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,824 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-12-16 10:48:51,824 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,824 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-12-16 10:48:51,824 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-12-16 10:48:51,824 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-015e7f4bb2df064fd'
2023-12-16 10:48:51,825 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd (recursive=True)
2023-12-16 10:48:51,828 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/handlers (recursive=False)
2023-12-16 10:48:51,839 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd (recursive=True)
2023-12-16 10:48:51,843 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/scripts (recursive=False)
2023-12-16 10:48:51,844 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd (recursive=True)
2023-12-16 10:48:51,859 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem (recursive=False)
2023-12-16 10:48:51,860 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-015e7f4bb2df064fd/datasource (quiet=False)
2023-12-16 10:48:51,860 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/datasource - wb: [644] 29 bytes
2023-12-16 10:48:51,860 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/datasource (recursive=False)
2023-12-16 10:48:51,861 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/datasource (recursive=False)
2023-12-16 10:48:51,861 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2023-12-16 10:48:51,862 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2023-12-16 10:48:51,863 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2023-12-16 10:48:51,863 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2023-12-16 10:48:51,863 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2023-12-16 10:48:51,863 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2023-12-16 10:48:51,864 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2023-12-16 10:48:51,864 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2023-12-16 10:48:51,864 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2023-12-16 10:48:51,865 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2023-12-16 10:48:51,865 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2023-12-16 10:48:51,865 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2023-12-16 10:48:51,866 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2023-12-16 10:48:51,867 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2023-12-16 10:48:51,867 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 13146 bytes
2023-12-16 10:48:51,868 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/obj.pkl (recursive=False)
2023-12-16 10:48:51,869 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/obj.pkl (recursive=False)
2023-12-16 10:48:51,879 - main.py[DEBUG]: [net] init will now be targeting instance id: i-015e7f4bb2df064fd. new=True
2023-12-16 10:48:51,879 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-12-16 10:48:51,879 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2023-12-16 10:48:51,879 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,887 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-12-16 10:48:51,887 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-12-16 10:48:51,887 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,888 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-12-16 10:48:51,888 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-12-16 10:48:51,888 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,900 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-12-16 10:48:51,900 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-12-16 10:48:51,900 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,904 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-12-16 10:48:51,904 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-12-16 10:48:51,904 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,905 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-12-16 10:48:51,905 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,906 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-12-16 10:48:51,907 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2023-12-16 10:48:51,907 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2023-12-16 10:48:51,907 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-12-16 10:48:51,907 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-12-16 10:48:51,907 - util.py[DEBUG]: Reading from /sys/class/net/enX0/name_assign_type (quiet=False)
2023-12-16 10:48:51,907 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/name_assign_type
2023-12-16 10:48:51,907 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2023-12-16 10:48:51,907 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/enX0/carrier (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/carrier
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/addr_assign_type
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/enX0/uevent
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2023-12-16 10:48:51,908 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2023-12-16 10:48:51,908 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2023-12-16 10:48:51,909 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2023-12-16 10:48:51,909 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2023-12-16 10:48:51,909 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-12-16 10:48:51,909 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-12-16 10:48:51,909 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2023-12-16 10:48:51,919 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2023-12-16 10:48:51,919 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/type
2023-12-16 10:48:51,919 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2023-12-16 10:48:51,919 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2023-12-16 10:48:51,919 - stages.py[DEBUG]: network config disabled by system_cfg
2023-12-16 10:48:51,919 - stages.py[INFO]: network config is disabled by system_cfg
2023-12-16 10:48:51,919 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2023-12-16 10:48:51,920 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2023-12-16 10:48:51,920 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt - wb: [600] 2476 bytes
2023-12-16 10:48:51,920 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt (recursive=False)
2023-12-16 10:48:51,921 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt (recursive=False)
2023-12-16 10:48:51,922 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:51,930 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt.i - wb: [600] 2498 bytes
2023-12-16 10:48:51,931 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt.i (recursive=False)
2023-12-16 10:48:51,932 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/user-data.txt.i (recursive=False)
2023-12-16 10:48:51,932 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt - wb: [600] 0 bytes
2023-12-16 10:48:51,932 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt (recursive=False)
2023-12-16 10:48:51,933 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt (recursive=False)
2023-12-16 10:48:51,934 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt.i - wb: [600] 308 bytes
2023-12-16 10:48:51,935 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt.i (recursive=False)
2023-12-16 10:48:51,935 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data.txt.i (recursive=False)
2023-12-16 10:48:51,936 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt - wb: [600] 0 bytes
2023-12-16 10:48:51,936 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt (recursive=False)
2023-12-16 10:48:51,937 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt (recursive=False)
2023-12-16 10:48:51,938 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt.i - wb: [600] 308 bytes
2023-12-16 10:48:51,939 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt.i (recursive=False)
2023-12-16 10:48:51,949 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/vendor-data2.txt.i (recursive=False)
2023-12-16 10:48:51,950 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-12-16 10:48:51,951 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-30-246.eu-central-1.compute.internal (ip-172-31-30-246)
2023-12-16 10:48:51,951 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-30-246.eu-central-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:52,105 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-30-246.eu-central-1.compute.internal
2023-12-16 10:48:52,106 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-30-246.eu-central-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:52,110 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmppn7ta6zs) - w: [644] 95 bytes/chars
2023-12-16 10:48:52,110 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/consume_data - wb: [644] 25 bytes
2023-12-16 10:48:52,111 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/consume_data (recursive=False)
2023-12-16 10:48:52,112 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/consume_data (recursive=False)
2023-12-16 10:48:52,113 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/consume_data'>)
2023-12-16 10:48:52,113 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2023-12-16 10:48:52,113 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2023-12-16 10:48:52,114 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2023-12-16 10:48:52,114 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2023-12-16 10:48:52,114 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,114 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,114 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,115 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,115 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,115 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2023-12-16 10:48:52,115 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2023-12-16 10:48:52,115 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2023-12-16 10:48:52,115 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,116 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2023-12-16 10:48:52,116 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2023-12-16 10:48:52,116 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2023-12-16 10:48:52,116 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1827 bytes
2023-12-16 10:48:52,117 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/scripts/user-data.txt (recursive=False)
2023-12-16 10:48:52,118 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/scripts/user-data.txt (recursive=False)
2023-12-16 10:48:52,118 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2023-12-16 10:48:52,129 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/cloud-config.txt - wb: [600] 154 bytes
2023-12-16 10:48:52,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/cloud-config.txt (recursive=False)
2023-12-16 10:48:52,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/cloud-config.txt (recursive=False)
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2023-12-16 10:48:52,131 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2023-12-16 10:48:52,131 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2023-12-16 10:48:52,131 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2023-12-16 10:48:52,131 - stages.py[DEBUG]: no vendordata from datasource
2023-12-16 10:48:52,131 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2023-12-16 10:48:52,131 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2023-12-16 10:48:52,132 - stages.py[DEBUG]: no vendordata2 from datasource
2023-12-16 10:48:52,132 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2023-12-16 10:48:52,132 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-12-16 10:48:52,132 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2023-12-16 10:48:52,132 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,150 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2023-12-16 10:48:52,150 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2023-12-16 10:48:52,150 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,151 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2023-12-16 10:48:52,151 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2023-12-16 10:48:52,151 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,153 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-12-16 10:48:52,153 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-12-16 10:48:52,153 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,156 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2023-12-16 10:48:52,157 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2023-12-16 10:48:52,157 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,158 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-12-16 10:48:52,158 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,159 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-12-16 10:48:52,159 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-12-16 10:48:52,159 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-12-16 10:48:52,159 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,170 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,170 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,253 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-12-16 10:48:52,253 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-12-16 10:48:52,253 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2023-12-16 10:48:52,256 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2023-12-16 10:48:52,257 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 17321 bytes
2023-12-16 10:48:52,270 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/obj.pkl (recursive=False)
2023-12-16 10:48:52,270 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/obj.pkl (recursive=False)
2023-12-16 10:48:52,271 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2023-12-16 10:48:52,271 - main.py[DEBUG]: no di_report found in config.
2023-12-16 10:48:52,273 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,273 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,275 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,275 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,279 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,279 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,289 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,289 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,292 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,292 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,294 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,294 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,300 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,301 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,310 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,310 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,319 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,319 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,322 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,322 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,324 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,324 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,329 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,329 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,331 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,331 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,339 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,339 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,342 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,342 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,349 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:52,349 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:52,351 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-12-16 10:48:52,352 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2023-12-16 10:48:52,352 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2023-12-16 10:48:52,352 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96ed90>)
2023-12-16 10:48:52,352 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2023-12-16 10:48:52,353 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2023-12-16 10:48:52,353 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2023-12-16 10:48:52,353 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2023-12-16 10:48:52,353 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_seed_random - wb: [644] 25 bytes
2023-12-16 10:48:52,354 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_seed_random (recursive=False)
2023-12-16 10:48:52,354 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_seed_random (recursive=False)
2023-12-16 10:48:52,355 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_seed_random'>)
2023-12-16 10:48:52,355 - cc_seed_random.py[DEBUG]: no command provided
2023-12-16 10:48:52,355 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2023-12-16 10:48:52,355 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2023-12-16 10:48:52,355 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2023-12-16 10:48:52,355 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96ed90>)
2023-12-16 10:48:52,355 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2023-12-16 10:48:52,355 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2023-12-16 10:48:52,356 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2023-12-16 10:48:52,356 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2023-12-16 10:48:52,356 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_files - wb: [644] 25 bytes
2023-12-16 10:48:52,356 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_files (recursive=False)
2023-12-16 10:48:52,357 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_files (recursive=False)
2023-12-16 10:48:52,358 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_files'>)
2023-12-16 10:48:52,358 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2023-12-16 10:48:52,358 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2023-12-16 10:48:52,358 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2023-12-16 10:48:52,358 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2023-12-16 10:48:52,358 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_metadata - wb: [644] 25 bytes
2023-12-16 10:48:52,359 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_metadata (recursive=False)
2023-12-16 10:48:52,369 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_metadata (recursive=False)
2023-12-16 10:48:52,370 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_write_metadata'>)
2023-12-16 10:48:52,370 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 12 bytes
2023-12-16 10:48:52,372 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2023-12-16 10:48:52,373 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2023-12-16 10:48:52,374 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2023-12-16 10:48:52,374 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2023-12-16 10:48:52,374 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2023-12-16 10:48:52,375 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2023-12-16 10:48:52,379 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2023-12-16 10:48:52,379 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2023-12-16 10:48:52,379 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2023-12-16 10:48:52,380 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2023-12-16 10:48:52,380 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96efa0>)
2023-12-16 10:48:52,380 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2023-12-16 10:48:52,380 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:52,393 - util.py[DEBUG]: Reading from /proc/2024/mountinfo (quiet=False)
2023-12-16 10:48:52,393 - util.py[DEBUG]: Read 2829 bytes from /proc/2024/mountinfo
2023-12-16 10:48:52,393 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2023-12-16 10:48:52,394 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2023-12-16 10:48:52,394 - util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
2023-12-16 10:48:52,394 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
2023-12-16 10:48:52,399 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:52,491 - subp.py[DEBUG]: Running command ['growpart', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:52,967 - util.py[DEBUG]: resize_devices took 0.575 seconds
2023-12-16 10:48:52,968 - cc_growpart.py[INFO]: '/' resized: changed (/dev/xvda, 1) from 8577334784 to 32199654912
2023-12-16 10:48:52,968 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2023-12-16 10:48:52,968 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2023-12-16 10:48:52,968 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2023-12-16 10:48:52,968 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96ed90>)
2023-12-16 10:48:52,969 - util.py[DEBUG]: Reading from /proc/2024/mountinfo (quiet=False)
2023-12-16 10:48:52,969 - util.py[DEBUG]: Read 2829 bytes from /proc/2024/mountinfo
2023-12-16 10:48:52,981 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2023-12-16 10:48:52,981 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2023-12-16 10:48:52,982 - util.py[DEBUG]: Forked child 2190 who will run callback log_time
2023-12-16 10:48:52,983 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2023-12-16 10:48:52,983 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2023-12-16 10:48:52,983 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2023-12-16 10:48:52,984 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2023-12-16 10:48:52,984 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_disk_setup - wb: [644] 25 bytes
2023-12-16 10:48:52,985 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_disk_setup (recursive=False)
2023-12-16 10:48:52,987 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_disk_setup (recursive=False)
2023-12-16 10:48:52,987 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_disk_setup'>)
2023-12-16 10:48:52,987 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2023-12-16 10:48:52,987 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2023-12-16 10:48:52,988 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2023-12-16 10:48:52,988 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_mounts - wb: [644] 24 bytes
2023-12-16 10:48:52,988 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_mounts (recursive=False)
2023-12-16 10:48:53,000 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:53,010 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_mounts (recursive=False)
2023-12-16 10:48:53,013 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_mounts'>)
2023-12-16 10:48:53,014 - cc_mounts.py[DEBUG]: mounts configuration is []
2023-12-16 10:48:53,019 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2023-12-16 10:48:53,019 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2023-12-16 10:48:53,020 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2023-12-16 10:48:53,020 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: changed default device swap => None
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: no need to setup swap
2023-12-16 10:48:53,020 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2023-12-16 10:48:53,020 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2023-12-16 10:48:53,032 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2023-12-16 10:48:53,033 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2023-12-16 10:48:53,033 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf994670>)
2023-12-16 10:48:53,034 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2023-12-16 10:48:53,035 - util.py[DEBUG]: Read 95 bytes from /var/lib/cloud/data/set-hostname
2023-12-16 10:48:53,035 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2023-12-16 10:48:53,035 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2023-12-16 10:48:53,035 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2023-12-16 10:48:53,035 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2023-12-16 10:48:53,035 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96ed90>)
2023-12-16 10:48:53,035 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-30-246.eu-central-1.compute.internal (ip-172-31-30-246)
2023-12-16 10:48:53,036 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:53,042 - util.py[DEBUG]: backgrounded Resizing took 0.042 seconds
2023-12-16 10:48:53,046 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-30-246.eu-central-1.compute.internal in 1 files
2023-12-16 10:48:53,046 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 46 bytes
2023-12-16 10:48:53,047 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2023-12-16 10:48:53,048 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2023-12-16 10:48:53,049 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2023-12-16 10:48:53,049 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2023-12-16 10:48:53,061 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2023-12-16 10:48:53,061 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f07bf96ebe0>)
2023-12-16 10:48:53,061 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2023-12-16 10:48:53,061 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2023-12-16 10:48:53,061 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2023-12-16 10:48:53,061 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2023-12-16 10:48:53,061 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ca_certs - wb: [644] 25 bytes
2023-12-16 10:48:53,062 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ca_certs (recursive=False)
2023-12-16 10:48:53,063 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ca_certs (recursive=False)
2023-12-16 10:48:53,063 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ca_certs'>)
2023-12-16 10:48:53,063 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2023-12-16 10:48:53,063 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2023-12-16 10:48:53,063 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2023-12-16 10:48:53,064 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2023-12-16 10:48:53,064 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_rsyslog - wb: [644] 25 bytes
2023-12-16 10:48:53,064 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_rsyslog (recursive=False)
2023-12-16 10:48:53,065 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_rsyslog (recursive=False)
2023-12-16 10:48:53,065 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_rsyslog'>)
2023-12-16 10:48:53,066 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2023-12-16 10:48:53,066 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2023-12-16 10:48:53,066 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2023-12-16 10:48:53,066 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2023-12-16 10:48:53,066 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_selinux - wb: [644] 25 bytes
2023-12-16 10:48:53,067 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_selinux (recursive=False)
2023-12-16 10:48:53,067 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_selinux (recursive=False)
2023-12-16 10:48:53,068 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_selinux'>)
2023-12-16 10:48:53,098 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2023-12-16 10:48:53,098 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2023-12-16 10:48:53,098 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2023-12-16 10:48:53,098 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2023-12-16 10:48:53,098 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2023-12-16 10:48:53,098 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2023-12-16 10:48:53,098 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2023-12-16 10:48:53,099 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2023-12-16 10:48:53,099 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_users_groups - wb: [644] 25 bytes
2023-12-16 10:48:53,100 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_users_groups (recursive=False)
2023-12-16 10:48:53,101 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_users_groups (recursive=False)
2023-12-16 10:48:53,101 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_users_groups'>)
2023-12-16 10:48:53,103 - __init__.py[INFO]: User ec2-user already exists, skipping.
2023-12-16 10:48:53,103 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:53,146 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2023-12-16 10:48:53,146 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2023-12-16 10:48:53,148 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2023-12-16 10:48:53,148 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2023-12-16 10:48:53,149 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2023-12-16 10:48:53,150 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2023-12-16 10:48:53,150 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2023-12-16 10:48:53,150 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2023-12-16 10:48:53,151 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ssh - wb: [644] 25 bytes
2023-12-16 10:48:53,151 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ssh (recursive=False)
2023-12-16 10:48:53,152 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ssh (recursive=False)
2023-12-16 10:48:53,153 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ssh'>)
2023-12-16 10:48:53,153 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:53,191 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2023-12-16 10:48:53,199 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:53,215 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2023-12-16 10:48:53,230 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2023-12-16 10:48:53,231 - util.py[DEBUG]: Read 133 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2023-12-16 10:48:53,231 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2023-12-16 10:48:53,231 - util.py[DEBUG]: Read 213 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2023-12-16 10:48:53,231 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-12-16 10:48:53,232 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-12-16 10:48:53,232 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2023-12-16 10:48:53,233 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2023-12-16 10:48:53,233 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2023-12-16 10:48:53,234 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,234 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,234 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2023-12-16 10:48:53,234 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2023-12-16 10:48:53,234 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2023-12-16 10:48:53,234 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 399 bytes
2023-12-16 10:48:53,235 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,235 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,235 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2023-12-16 10:48:53,239 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-12-16 10:48:53,239 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-12-16 10:48:53,240 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2023-12-16 10:48:53,249 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-12-16 10:48:53,250 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,250 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,250 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2023-12-16 10:48:53,250 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2023-12-16 10:48:53,250 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2023-12-16 10:48:53,250 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 565 bytes
2023-12-16 10:48:53,251 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,251 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2023-12-16 10:48:53,251 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2023-12-16 10:48:53,252 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2023-12-16 10:48:53,252 - main.py[DEBUG]: Ran 17 modules with 0 failures
2023-12-16 10:48:53,253 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpbscme6zh) - w: [644] 485 bytes/chars
2023-12-16 10:48:53,253 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-12-16 10:48:53,253 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2023-12-16 10:48:53,253 - util.py[DEBUG]: cloud-init mode 'init' took 2.359 seconds (2.36)
2023-12-16 10:48:53,253 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2023-12-16 10:48:54,501 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Sat, 16 Dec 2023 10:48:54 +0000. Up 9.34 seconds.
2023-12-16 10:48:54,503 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,503 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,513 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,513 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,519 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,519 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,521 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,521 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,529 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,529 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,531 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,531 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,533 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,534 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,539 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,539 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,541 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,541 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,551 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:54,551 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:54,553 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-12-16 10:48:54,553 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2023-12-16 10:48:54,553 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2023-12-16 10:48:54,554 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2023-12-16 10:48:54,554 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_keyboard - wb: [644] 25 bytes
2023-12-16 10:48:54,556 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_keyboard (recursive=False)
2023-12-16 10:48:54,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_keyboard (recursive=False)
2023-12-16 10:48:54,558 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_keyboard'>)
2023-12-16 10:48:54,558 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2023-12-16 10:48:54,558 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2023-12-16 10:48:54,558 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2023-12-16 10:48:54,559 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2023-12-16 10:48:54,559 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_locale - wb: [644] 25 bytes
2023-12-16 10:48:54,566 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_locale (recursive=False)
2023-12-16 10:48:54,566 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_locale (recursive=False)
2023-12-16 10:48:54,567 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_locale'>)
2023-12-16 10:48:54,567 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2023-12-16 10:48:54,567 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2023-12-16 10:48:54,567 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2023-12-16 10:48:54,567 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2023-12-16 10:48:54,567 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2023-12-16 10:48:54,568 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2023-12-16 10:48:54,571 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2023-12-16 10:48:54,572 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2023-12-16 10:48:54,573 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2023-12-16 10:48:54,573 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2023-12-16 10:48:54,573 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2023-12-16 10:48:54,573 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_set_passwords - wb: [644] 25 bytes
2023-12-16 10:48:54,574 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_set_passwords (recursive=False)
2023-12-16 10:48:54,574 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_set_passwords (recursive=False)
2023-12-16 10:48:54,575 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_set_passwords'>)
2023-12-16 10:48:54,575 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2023-12-16 10:48:54,605 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-12-16 10:48:54,605 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2023-12-16 10:48:54,605 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2023-12-16 10:48:54,605 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2023-12-16 10:48:54,606 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2023-12-16 10:48:54,606 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2023-12-16 10:48:54,606 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2023-12-16 10:48:54,606 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_variables - wb: [644] 25 bytes
2023-12-16 10:48:54,607 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_variables (recursive=False)
2023-12-16 10:48:54,608 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_variables (recursive=False)
2023-12-16 10:48:54,608 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_variables'>)
2023-12-16 10:48:54,608 - cc_yum_variables.py[INFO]: handling yum-variables
2023-12-16 10:48:54,608 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.2, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2023-12-16 10:48:54,609 - cc_yum_variables.py[INFO]: No yum vars to delete
2023-12-16 10:48:54,609 - cc_yum_variables.py[INFO]: No yum vars to set
2023-12-16 10:48:54,609 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2023-12-16 10:48:54,609 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2023-12-16 10:48:54,619 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2023-12-16 10:48:54,619 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_add_repo - wb: [644] 24 bytes
2023-12-16 10:48:54,620 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_add_repo (recursive=False)
2023-12-16 10:48:54,620 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_add_repo (recursive=False)
2023-12-16 10:48:54,621 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_yum_add_repo'>)
2023-12-16 10:48:54,621 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2023-12-16 10:48:54,621 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2023-12-16 10:48:54,621 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2023-12-16 10:48:54,621 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2023-12-16 10:48:54,621 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ntp - wb: [644] 25 bytes
2023-12-16 10:48:54,622 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ntp (recursive=False)
2023-12-16 10:48:54,623 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ntp (recursive=False)
2023-12-16 10:48:54,623 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_ntp'>)
2023-12-16 10:48:54,623 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2023-12-16 10:48:54,623 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2023-12-16 10:48:54,623 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2023-12-16 10:48:54,623 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2023-12-16 10:48:54,624 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_timezone - wb: [644] 25 bytes
2023-12-16 10:48:54,624 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_timezone (recursive=False)
2023-12-16 10:48:54,625 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_timezone (recursive=False)
2023-12-16 10:48:54,625 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_timezone'>)
2023-12-16 10:48:54,625 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2023-12-16 10:48:54,625 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2023-12-16 10:48:54,625 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2023-12-16 10:48:54,626 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2023-12-16 10:48:54,626 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f70a31e3340>)
2023-12-16 10:48:54,626 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2023-12-16 10:48:54,626 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2023-12-16 10:48:54,626 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2023-12-16 10:48:54,626 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2023-12-16 10:48:54,626 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_runcmd - wb: [644] 24 bytes
2023-12-16 10:48:54,627 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_runcmd (recursive=False)
2023-12-16 10:48:54,627 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_runcmd (recursive=False)
2023-12-16 10:48:54,628 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-015e7f4bb2df064fd/sem/config_runcmd'>)
2023-12-16 10:48:54,628 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2023-12-16 10:48:54,628 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2023-12-16 10:48:54,628 - main.py[DEBUG]: Ran 9 modules with 0 failures
2023-12-16 10:48:54,628 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp5t9rtmi_) - w: [644] 513 bytes/chars
2023-12-16 10:48:54,629 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-12-16 10:48:54,629 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2023-12-16 10:48:54,629 - util.py[DEBUG]: cloud-init mode 'modules' took 0.289 seconds (0.28)
2023-12-16 10:48:54,629 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2023-12-16 10:48:55,539 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Sat, 16 Dec 2023 10:48:55 +0000. Up 10.38 seconds.
2023-12-16 10:48:55,541 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-12-16 10:48:55,542 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-12-16 10:48:55,543 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2023-12-16 10:48:55,544 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2023-12-16 10:48:55,544 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2023-12-16 10:48:55,544 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f1a683a8e20>)
2023-12-16 10:48:55,544 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2023-12-16 10:49:10,459 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2023-12-16 10:49:10,460 - main.py[DEBUG]: Ran 1 modules with 0 failures
2023-12-16 10:49:10,460 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpu22q0_ki) - w: [644] 541 bytes/chars
2023-12-16 10:49:10,461 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpwnz5wmfl) - w: [644] 64 bytes/chars
2023-12-16 10:49:10,461 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2023-12-16 10:49:10,461 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-12-16 10:49:10,461 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2023-12-16 10:49:10,461 - util.py[DEBUG]: cloud-init mode 'modules' took 15.079 seconds (15.08)
2023-12-16 10:49:10,461 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
